export const eventLog = [
  {
    id: "event-1",
    event_path: "jasuindo.Taiyo1.Alarm/Event/Alarm/MachineSpeedHigh",
    start_ts: "2023-08-01T09:00:00.000Z",
    end_ts: "",
    status: "open",
    activity: "Setup",
    activity_label: "Setting Oil Pump",
    severity: "info",
    notes_on_open: "WO WO/2023/01/001 WO/2023/01/001WO/2023/01/001WO/2023/01/001 Loaded",
    notes_on_close: "WO WO/2023/01/001 Unloaded",
    context: {
      operatorLabel: "Budi",
      speed: 100,
      threshold: 50,
    },
  },
  {
    id: "event-2",
    event_path: "jasuindo.Taiyo1.Alarm/Event/Alarm/MachineSpeedHigh",
    start_ts: "2023-08-01T08:00:00.000Z",
    end_ts: "2023-08-01T09:00:00.000Z",
    status: "closed",
    activity: "Setup",
    activity_label: "Setting Converter",
    severity: "medium",
    notes_on_open: "WO WO/2023/01/001 Loaded",
    notes_on_close: "WO WO/2023/01/001 Unloaded",
    context: {
      operatorLabel: "Budi",
      speed: 100,
      threshold: 50,
    },
  },
  {
    id: "event-3",
    event_path: "jasuindo.Taiyo1.Alarm/Event/Alarm/MachineSpeedHigh",
    start_ts: "2023-08-01T00:00:00.000Z",
    end_ts: "",
    status: "open",
    activity: "Setup",
    activity_label: "Setting Sensor",
    severity: "low",
    notes_on_open: "WO WO/2023/01/001 Loaded",
    notes_on_close: "WO WO/2023/01/001 Unloaded",
    context: {
      operatorLabel: "Joni",
      speed: 100,
      threshold: 50,
    },
  },
  {
    id: "event-4",
    event_path: "jasuindo.Taiyo1.Alarm/Event/Alarm/MachineSpeedHigh",
    start_ts: "2023-08-01T08:00:00.000Z",
    end_ts: "2023-08-01T09:00:00.000Z",
    status: "closed",
    activity: "Setup",
    activity_label: "Setting Converter",
    severity: "medium",
    notes_on_open: "WO WO/2023/01/001 Loaded",
    notes_on_close: "WO WO/2023/01/001 Unloaded",
    context: {
      operatorLabel: "Budi",
      speed: 100,
      threshold: 50,
    },
  },
  {
    id: "event-5",
    event_path: "jasuindo.Taiyo1.Alarm/Event/Alarm/MachineSpeedHigh",
    start_ts: "2023-08-01T00:00:00.000Z",
    end_ts: "",
    status: "open",
    activity: "Setup",
    activity_label: "Setting Sensor",
    severity: "low",
    notes_on_open: "WO WO/2023/01/001 Loaded",
    notes_on_close: "WO WO/2023/01/001 Unloaded",
    context: {
      operatorLabel: "Joni",
      speed: 100,
      threshold: 50,
    },
  },
  {
    id: "event-6",
    event_path: "jasuindo.Taiyo1.Alarm/Event/Alarm/MachineSpeedHigh",
    start_ts: "2023-08-01T00:00:00.000Z",
    end_ts: "",
    status: "open",
    activity: "Setup",
    activity_label: "Setting Sensor",
    severity: "low",
    notes_on_open: "WO WO/2023/01/001 Loaded",
    notes_on_close: "WO WO/2023/01/001 Unloaded",
    context: {
      operatorLabel: "Joni",
      speed: 100,
      threshold: 50,
    },
  },
];

export const eventPallete = [
  {
    id: 1,
    lookup_type: "EVENT_PALLETE",
    code: "SETUP_MATERIAL_CHECK",
    label: "001 - Material Check",
    description: "Verify material before machine setup",
    sort_order: 1,
    is_active: true,
    attribute: {
      category: "Setup",
    },
  },
  {
    id: 2,
    lookup_type: "EVENT_PALLETE",
    code: "SETUP_SENSOR_ALIGNMENT",
    label: "002 - Sensor Alignment",
    description: "Align sensor during setup process",
    sort_order: 2,
    is_active: true,
    attribute: {
      category: "Setup",
    },
  },
  {
    id: 3,
    lookup_type: "EVENT_PALLETE",
    code: "SETUP_TOOL_CHANGE",
    label: "003 - Tool Change",
    description: "Replace tooling before production start",
    sort_order: 3,
    is_active: true,
    attribute: {
      category: "Setup",
    },
  },
  {
    id: 4,
    lookup_type: "EVENT_PALLETE",
    code: "SETUP_MACHINE_WARMUP",
    label: "004 - Machine Warmup",
    description: "Warm up machine to operating condition",
    sort_order: 4,
    is_active: true,
    attribute: {
      category: "Setup",
    },
  },
  {
    id: 5,
    lookup_type: "EVENT_PALLETE",
    code: "SETUP_QUALITY_TRIAL",
    label: "005 - Quality Trial",
    description: "Run first trial and verify quality result",
    sort_order: 5,
    is_active: true,
    attribute: {
      category: "Setup",
    },
  },
  {
    id: 6,
    lookup_type: "EVENT_PALLETE",
    code: "PROD_RUNNING_NORMAL",
    label: "001 - Running Normal",
    description: "Machine running in normal production state",
    sort_order: 6,
    is_active: true,
    attribute: {
      category: "Production",
    },
  },
  {
    id: 7,
    lookup_type: "EVENT_PALLETE",
    code: "PROD_SPEED_ADJUSTMENT",
    label: "002 - Speed Adjustment",
    description: "Adjust machine speed during production",
    sort_order: 7,
    is_active: true,
    attribute: {
      category: "Production",
    },
  },
  {
    id: 8,
    lookup_type: "EVENT_PALLETE",
    code: "PROD_BATCH_COMPLETED",
    label: "003 - Batch Completed",
    description: "Production batch has been completed",
    sort_order: 8,
    is_active: true,
    attribute: {
      category: "Production",
    },
  },
  {
    id: 9,
    lookup_type: "EVENT_PALLETE",
    code: "IDLE_WAITING_MATERIAL",
    label: "001 - Waiting Material",
    description: "Machine idle while waiting for material",
    sort_order: 9,
    is_active: true,
    attribute: {
      category: "Idle",
    },
  },
  {
    id: 10,
    lookup_type: "EVENT_PALLETE",
    code: "IDLE_WAITING_OPERATOR",
    label: "002 - Waiting Operator",
    description: "Machine idle waiting for operator action",
    sort_order: 10,
    is_active: true,
    attribute: {
      category: "Idle",
    },
  },
  {
    id: 11,
    lookup_type: "EVENT_PALLETE",
    code: "IDLE_MINOR_STOPPAGE",
    label: "003 - Minor Stoppage",
    description: "Short idle due to minor stoppage",
    sort_order: 11,
    is_active: true,
    attribute: {
      category: "Idle",
    },
  },
  {
    id: 12,
    lookup_type: "EVENT_PALLETE",
    code: "IDLE_CHANGEOVER_PREP",
    label: "004 - Changeover Prep",
    description: "Idle state for next changeover preparation",
    sort_order: 12,
    is_active: true,
    attribute: {
      category: "Idle",
    },
  },
  {
    id: 13,
    lookup_type: "EVENT_PALLETE",
    code: "IDLE_POWER_FLUCTUATION",
    label: "005 - Power Fluctuation",
    description: "Idle due to unstable power condition",
    sort_order: 13,
    is_active: true,
    attribute: {
      category: "Idle",
    },
  },
  {
    id: 14,
    lookup_type: "EVENT_PALLETE",
    code: "IDLE_AIR_PRESSURE_LOW",
    label: "006 - Low Air Pressure",
    description: "Idle due to low compressed air pressure",
    sort_order: 14,
    is_active: true,
    attribute: {
      category: "Idle",
    },
  },
  {
    id: 15,
    lookup_type: "EVENT_PALLETE",
    code: "IDLE_MATERIAL_JAM_CLEARING",
    label: "007 - Clearing Jam",
    description: "Idle while clearing material jam",
    sort_order: 15,
    is_active: true,
    attribute: {
      category: "Idle",
    },
  },
  {
    id: 16,
    lookup_type: "EVENT_PALLETE",
    code: "IDLE_QUALITY_RECHECK",
    label: "008 - Quality Recheck",
    description: "Idle for additional quality recheck",
    sort_order: 16,
    is_active: true,
    attribute: {
      category: "Idle",
    },
  },
  {
    id: 17,
    lookup_type: "EVENT_PALLETE",
    code: "IDLE_SHIFT_HANDOVER",
    label: "009 - Shift Handover",
    description: "Idle during shift handover process",
    sort_order: 17,
    is_active: true,
    attribute: {
      category: "Idle",
    },
  },
  {
    id: 18,
    lookup_type: "EVENT_PALLETE",
    code: "IDLE_CLEANING_AREA",
    label: "010 - Cleaning Area",
    description: "Idle while operator cleans machine area",
    sort_order: 18,
    is_active: true,
    attribute: {
      category: "Idle",
    },
  },
];
