/* tslint:disable */
/* eslint-disable */
/**
 * Optimes NEST API
 * OptiMES API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AccountControllerCreate201Response {
    'account'?: AccountResponseDto;
    'initial_password'?: string;
}
export interface AccountResponseDto {
    'id': string;
    'username': string;
    'full_name': string;
    'phone_number'?: string;
    'email'?: string;
    'attribute'?: object;
    /**
     * Populated lookup object for account_lifecycle
     */
    'account_lifecycle': LookupResponseDto;
    /**
     * Populated lookup object for account_type
     */
    'account_type': LookupResponseDto;
    /**
     * Populated lookup object for account_role
     */
    'account_role'?: LookupResponseDto;
    'account_expiry_date'?: string;
    'password_last_changed'?: string;
    'password_expiry_time'?: string;
    'must_change_password': boolean;
    'last_login_time'?: string;
}
export interface CreateAccountDto {
    /**
     * Username rules: unique, lowercase, alphanumeric + underscore, length 4–20, regex ^[a-z][a-z0-9_]{3,19}$
     */
    'username': string;
    'full_name': string;
    'phone_number'?: string;
    'email'?: string;
    'attribute'?: object;
    /**
     * Lookup id for account_type (int). If WITH_EXPIRATION, account_expiry_date is required.
     */
    'account_type': number;
    /**
     * Lookup id for account_role (int)
     */
    'account_role': number;
    /**
     * Required if account_type is WITH_EXPIRATION. Must be null for PERMANENT.
     */
    'account_expiry_date'?: string;
}
export interface CreateLookupDto {
    'lookup_type': string;
    'code': string;
    'label': string;
    'description'?: string;
    'sort_order'?: number;
    'is_active'?: boolean;
    'attribute'?: object;
}
export interface EditRoleDto {
    /**
     * Lookup id for account_role (number or string)
     */
    'roleLookupId': object;
}
export interface LoginDto {
    'username': string;
    'password': string;
}
export interface LookupControllerActivateRequest {
    'is_active'?: boolean;
}
export interface LookupResponseDto {
    'id': number;
    'lookup_type': string;
    'code': string;
    'label': string;
    'description'?: string;
    'sort_order'?: number;
    'is_active': boolean;
    'attribute'?: object;
}
export interface ResetPasswordDto {
    /**
     * Password complexity: min 12 chars, upper/lower/number/symbol. Regex: ^(?=.*[a-z])(?=.*[A-Z])(?=.*d)(?=.*[@$!%*?&#^()_+-=[]{}|;:,.<>])[A-Za-zd@$!%*?&#^()_+-=[]{}|;:,.<>]{12,}$
     */
    'newPassword': string;
}
export interface UpdateLookupDto {
    'lookup_type'?: string;
    'code'?: string;
    'label'?: string;
    'description'?: string;
    'sort_order'?: number;
    'is_active'?: boolean;
    'attribute'?: object;
}

/**
 * AccountsApi - axios parameter creator
 */
export const AccountsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Account is always created with lifecycle = CREATED, must_change_password = true, password_last_changed = null. Initial password is generated by system.
         * @summary Create account
         * @param {CreateAccountDto} createAccountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerCreate: async (createAccountDto: CreateAccountDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createAccountDto' is not null or undefined
            assertParamExists('accountControllerCreate', 'createAccountDto', createAccountDto)
            const localVarPath = `/api/accounts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createAccountDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Soft delete account (mark DELETED)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('accountControllerDelete', 'id', id)
            const localVarPath = `/api/accounts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Disable account
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerDisable: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('accountControllerDisable', 'id', id)
            const localVarPath = `/api/accounts/{id}/disable`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Edit account role
         * @param {string} id Account ID (UUID)
         * @param {EditRoleDto} editRoleDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerEditRole: async (id: string, editRoleDto: EditRoleDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('accountControllerEditRole', 'id', id)
            // verify required parameter 'editRoleDto' is not null or undefined
            assertParamExists('accountControllerEditRole', 'editRoleDto', editRoleDto)
            const localVarPath = `/api/accounts/{id}/role`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(editRoleDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Enable account
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerEnable: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('accountControllerEnable', 'id', id)
            const localVarPath = `/api/accounts/{id}/enable`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all accounts (password excluded)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerGetAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/accounts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get account by id (password excluded)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerGetById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('accountControllerGetById', 'id', id)
            const localVarPath = `/api/accounts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * If lifecycle=CREATED, response is 200 with must_change_password=true. DISABLED/EXPIRED => 403. DELETED => 404.
         * @summary Login (sets cookie accountId)
         * @param {LoginDto} loginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerLogin: async (loginDto: LoginDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginDto' is not null or undefined
            assertParamExists('accountControllerLogin', 'loginDto', loginDto)
            const localVarPath = `/api/accounts/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout (clears cookie accountId)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerLogout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/accounts/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * If lifecycle=CREATED and password change succeeds, lifecycle becomes ACTIVE; must_change_password=false; password_last_changed set.
         * @summary Reset password (admin or self)
         * @param {string} id 
         * @param {ResetPasswordDto} resetPasswordDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerResetPassword: async (id: string, resetPasswordDto: ResetPasswordDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('accountControllerResetPassword', 'id', id)
            // verify required parameter 'resetPasswordDto' is not null or undefined
            assertParamExists('accountControllerResetPassword', 'resetPasswordDto', resetPasswordDto)
            const localVarPath = `/api/accounts/{id}/reset-password`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(resetPasswordDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Validate cookie and return account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerValidate: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/accounts/validate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccountsApi - functional programming interface
 */
export const AccountsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccountsApiAxiosParamCreator(configuration)
    return {
        /**
         * Account is always created with lifecycle = CREATED, must_change_password = true, password_last_changed = null. Initial password is generated by system.
         * @summary Create account
         * @param {CreateAccountDto} createAccountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerCreate(createAccountDto: CreateAccountDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountControllerCreate201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerCreate(createAccountDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Soft delete account (mark DELETED)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountControllerDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Disable account
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerDisable(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerDisable(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountControllerDisable']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Edit account role
         * @param {string} id Account ID (UUID)
         * @param {EditRoleDto} editRoleDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerEditRole(id: string, editRoleDto: EditRoleDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerEditRole(id, editRoleDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountControllerEditRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Enable account
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerEnable(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerEnable(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountControllerEnable']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all accounts (password excluded)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerGetAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AccountResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerGetAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountControllerGetAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get account by id (password excluded)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerGetById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerGetById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountControllerGetById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * If lifecycle=CREATED, response is 200 with must_change_password=true. DISABLED/EXPIRED => 403. DELETED => 404.
         * @summary Login (sets cookie accountId)
         * @param {LoginDto} loginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerLogin(loginDto: LoginDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerLogin(loginDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountControllerLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout (clears cookie accountId)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerLogout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerLogout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountControllerLogout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * If lifecycle=CREATED and password change succeeds, lifecycle becomes ACTIVE; must_change_password=false; password_last_changed set.
         * @summary Reset password (admin or self)
         * @param {string} id 
         * @param {ResetPasswordDto} resetPasswordDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerResetPassword(id: string, resetPasswordDto: ResetPasswordDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerResetPassword(id, resetPasswordDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountControllerResetPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Validate cookie and return account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerValidate(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerValidate(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountControllerValidate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccountsApi - factory interface
 */
export const AccountsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccountsApiFp(configuration)
    return {
        /**
         * Account is always created with lifecycle = CREATED, must_change_password = true, password_last_changed = null. Initial password is generated by system.
         * @summary Create account
         * @param {CreateAccountDto} createAccountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerCreate(createAccountDto: CreateAccountDto, options?: RawAxiosRequestConfig): AxiosPromise<AccountControllerCreate201Response> {
            return localVarFp.accountControllerCreate(createAccountDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Soft delete account (mark DELETED)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountControllerDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Disable account
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerDisable(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountControllerDisable(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Edit account role
         * @param {string} id Account ID (UUID)
         * @param {EditRoleDto} editRoleDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerEditRole(id: string, editRoleDto: EditRoleDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountControllerEditRole(id, editRoleDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Enable account
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerEnable(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountControllerEnable(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all accounts (password excluded)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerGetAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<AccountResponseDto>> {
            return localVarFp.accountControllerGetAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get account by id (password excluded)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerGetById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<AccountResponseDto> {
            return localVarFp.accountControllerGetById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * If lifecycle=CREATED, response is 200 with must_change_password=true. DISABLED/EXPIRED => 403. DELETED => 404.
         * @summary Login (sets cookie accountId)
         * @param {LoginDto} loginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerLogin(loginDto: LoginDto, options?: RawAxiosRequestConfig): AxiosPromise<AccountResponseDto> {
            return localVarFp.accountControllerLogin(loginDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout (clears cookie accountId)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerLogout(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountControllerLogout(options).then((request) => request(axios, basePath));
        },
        /**
         * If lifecycle=CREATED and password change succeeds, lifecycle becomes ACTIVE; must_change_password=false; password_last_changed set.
         * @summary Reset password (admin or self)
         * @param {string} id 
         * @param {ResetPasswordDto} resetPasswordDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerResetPassword(id: string, resetPasswordDto: ResetPasswordDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountControllerResetPassword(id, resetPasswordDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Validate cookie and return account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerValidate(options?: RawAxiosRequestConfig): AxiosPromise<AccountResponseDto> {
            return localVarFp.accountControllerValidate(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccountsApi - object-oriented interface
 */
export class AccountsApi extends BaseAPI {
    /**
     * Account is always created with lifecycle = CREATED, must_change_password = true, password_last_changed = null. Initial password is generated by system.
     * @summary Create account
     * @param {CreateAccountDto} createAccountDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerCreate(createAccountDto: CreateAccountDto, options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountControllerCreate(createAccountDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Soft delete account (mark DELETED)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerDelete(id: string, options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountControllerDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Disable account
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerDisable(id: string, options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountControllerDisable(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Edit account role
     * @param {string} id Account ID (UUID)
     * @param {EditRoleDto} editRoleDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerEditRole(id: string, editRoleDto: EditRoleDto, options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountControllerEditRole(id, editRoleDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Enable account
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerEnable(id: string, options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountControllerEnable(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all accounts (password excluded)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerGetAll(options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountControllerGetAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get account by id (password excluded)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerGetById(id: string, options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountControllerGetById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * If lifecycle=CREATED, response is 200 with must_change_password=true. DISABLED/EXPIRED => 403. DELETED => 404.
     * @summary Login (sets cookie accountId)
     * @param {LoginDto} loginDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerLogin(loginDto: LoginDto, options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountControllerLogin(loginDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout (clears cookie accountId)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerLogout(options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountControllerLogout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * If lifecycle=CREATED and password change succeeds, lifecycle becomes ACTIVE; must_change_password=false; password_last_changed set.
     * @summary Reset password (admin or self)
     * @param {string} id 
     * @param {ResetPasswordDto} resetPasswordDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerResetPassword(id: string, resetPasswordDto: ResetPasswordDto, options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountControllerResetPassword(id, resetPasswordDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Validate cookie and return account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerValidate(options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountControllerValidate(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HealthApi - axios parameter creator
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHealth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerGetHealth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerGetHealth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.appControllerGetHealth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHealth(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.appControllerGetHealth(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 */
export class HealthApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public appControllerGetHealth(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).appControllerGetHealth(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * LookupsApi - axios parameter creator
 */
export const LookupsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Activate or deactivate a lookup
         * @param {string} id Lookup id (uuid)
         * @param {LookupControllerActivateRequest} lookupControllerActivateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lookupControllerActivate: async (id: string, lookupControllerActivateRequest: LookupControllerActivateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('lookupControllerActivate', 'id', id)
            // verify required parameter 'lookupControllerActivateRequest' is not null or undefined
            assertParamExists('lookupControllerActivate', 'lookupControllerActivateRequest', lookupControllerActivateRequest)
            const localVarPath = `/api/lookups/{id}/activate`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(lookupControllerActivateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new lookup
         * @param {CreateLookupDto} createLookupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lookupControllerCreate: async (createLookupDto: CreateLookupDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createLookupDto' is not null or undefined
            assertParamExists('lookupControllerCreate', 'createLookupDto', createLookupDto)
            const localVarPath = `/api/lookups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createLookupDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List lookups
         * @param {string} [type] Filter by lookup_type (e.g. ACCOUNT_LIFECYCLE)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lookupControllerFindAll: async (type?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/lookups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get lookup by id
         * @param {string} id Lookup id (uuid)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lookupControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('lookupControllerFindOne', 'id', id)
            const localVarPath = `/api/lookups/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Replace an existing lookup
         * @param {string} id Lookup id (uuid)
         * @param {UpdateLookupDto} updateLookupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lookupControllerUpdate: async (id: string, updateLookupDto: UpdateLookupDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('lookupControllerUpdate', 'id', id)
            // verify required parameter 'updateLookupDto' is not null or undefined
            assertParamExists('lookupControllerUpdate', 'updateLookupDto', updateLookupDto)
            const localVarPath = `/api/lookups/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateLookupDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LookupsApi - functional programming interface
 */
export const LookupsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LookupsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Activate or deactivate a lookup
         * @param {string} id Lookup id (uuid)
         * @param {LookupControllerActivateRequest} lookupControllerActivateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lookupControllerActivate(id: string, lookupControllerActivateRequest: LookupControllerActivateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LookupResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.lookupControllerActivate(id, lookupControllerActivateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LookupsApi.lookupControllerActivate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new lookup
         * @param {CreateLookupDto} createLookupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lookupControllerCreate(createLookupDto: CreateLookupDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LookupResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.lookupControllerCreate(createLookupDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LookupsApi.lookupControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List lookups
         * @param {string} [type] Filter by lookup_type (e.g. ACCOUNT_LIFECYCLE)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lookupControllerFindAll(type?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LookupResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.lookupControllerFindAll(type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LookupsApi.lookupControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get lookup by id
         * @param {string} id Lookup id (uuid)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lookupControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LookupResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.lookupControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LookupsApi.lookupControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Replace an existing lookup
         * @param {string} id Lookup id (uuid)
         * @param {UpdateLookupDto} updateLookupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lookupControllerUpdate(id: string, updateLookupDto: UpdateLookupDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LookupResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.lookupControllerUpdate(id, updateLookupDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LookupsApi.lookupControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LookupsApi - factory interface
 */
export const LookupsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LookupsApiFp(configuration)
    return {
        /**
         * 
         * @summary Activate or deactivate a lookup
         * @param {string} id Lookup id (uuid)
         * @param {LookupControllerActivateRequest} lookupControllerActivateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lookupControllerActivate(id: string, lookupControllerActivateRequest: LookupControllerActivateRequest, options?: RawAxiosRequestConfig): AxiosPromise<LookupResponseDto> {
            return localVarFp.lookupControllerActivate(id, lookupControllerActivateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new lookup
         * @param {CreateLookupDto} createLookupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lookupControllerCreate(createLookupDto: CreateLookupDto, options?: RawAxiosRequestConfig): AxiosPromise<LookupResponseDto> {
            return localVarFp.lookupControllerCreate(createLookupDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List lookups
         * @param {string} [type] Filter by lookup_type (e.g. ACCOUNT_LIFECYCLE)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lookupControllerFindAll(type?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<LookupResponseDto>> {
            return localVarFp.lookupControllerFindAll(type, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get lookup by id
         * @param {string} id Lookup id (uuid)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lookupControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<LookupResponseDto> {
            return localVarFp.lookupControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Replace an existing lookup
         * @param {string} id Lookup id (uuid)
         * @param {UpdateLookupDto} updateLookupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lookupControllerUpdate(id: string, updateLookupDto: UpdateLookupDto, options?: RawAxiosRequestConfig): AxiosPromise<LookupResponseDto> {
            return localVarFp.lookupControllerUpdate(id, updateLookupDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LookupsApi - object-oriented interface
 */
export class LookupsApi extends BaseAPI {
    /**
     * 
     * @summary Activate or deactivate a lookup
     * @param {string} id Lookup id (uuid)
     * @param {LookupControllerActivateRequest} lookupControllerActivateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public lookupControllerActivate(id: string, lookupControllerActivateRequest: LookupControllerActivateRequest, options?: RawAxiosRequestConfig) {
        return LookupsApiFp(this.configuration).lookupControllerActivate(id, lookupControllerActivateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new lookup
     * @param {CreateLookupDto} createLookupDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public lookupControllerCreate(createLookupDto: CreateLookupDto, options?: RawAxiosRequestConfig) {
        return LookupsApiFp(this.configuration).lookupControllerCreate(createLookupDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List lookups
     * @param {string} [type] Filter by lookup_type (e.g. ACCOUNT_LIFECYCLE)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public lookupControllerFindAll(type?: string, options?: RawAxiosRequestConfig) {
        return LookupsApiFp(this.configuration).lookupControllerFindAll(type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get lookup by id
     * @param {string} id Lookup id (uuid)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public lookupControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return LookupsApiFp(this.configuration).lookupControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Replace an existing lookup
     * @param {string} id Lookup id (uuid)
     * @param {UpdateLookupDto} updateLookupDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public lookupControllerUpdate(id: string, updateLookupDto: UpdateLookupDto, options?: RawAxiosRequestConfig) {
        return LookupsApiFp(this.configuration).lookupControllerUpdate(id, updateLookupDto, options).then((request) => request(this.axios, this.basePath));
    }
}



